/*
 * This is an autogenerated stub. 
 * Do not change it manually. 
 */

# include <stdint.h>
# include <stdbool.h>
# include "../../../src/middleware/include/middleware.h"
# include "traffic_speed.h"

# define ADDR_SKELETON_INPUTS 0
# define ADDR_COMPUTATION_ENABLE 100

static void model_compute(bool enable);
static uint8_t get_id(void);

static uint64_t accelerator_id = 47;
static uint32_t accelerator_addr = 4000;

bool traffic_speed_deploy(void)
{
   middlewareInit();
   middlewareConfigureFpga(accelerator_addr);
   sleep_ms(200);
   bool is_deployed_successfully = (get_id() == accelerator_id);
   middlewareDeinit();
   return is_deployed_successfully;
}

int8_t traffic_speed_predict(int8_t *inputs, bool more_inputs)
{
   int8_t _result;

   middlewareInit();
   middlewareUserlogicEnable();
   middlewareWriteBlocking(ADDR_SKELETON_INPUTS+0, (uint8_t*)(inputs), 6);
   middlewareWriteBlocking(ADDR_SKELETON_INPUTS+6, (uint8_t*)(&more_inputs), 1);
   model_compute(true);

   while( middlewareUserlogicGetBusyStatus() );

   middlewareReadBlocking(1, (uint8_t *)(&_result), 1);
   middlewareReadBlocking(1, (uint8_t *)(&_result), 1);
   model_compute(false);
   middlewareUserlogicDisable();
   middlewareDeinit();
   return _result;
}

static void model_compute(bool enable)
{
   uint8_t cmd = (enable ? 1 : 0);
   middlewareWriteBlocking(ADDR_COMPUTATION_ENABLE, &cmd, 1);
}

static uint8_t get_id(void)
{
   middlewareUserlogicEnable();
   uint8_t id = middlewareGetDesignId();
   middlewareUserlogicDisable();
   return id;
}

